landing page
kalviumcommunity/ClosetGenie pull request #1
Opened 2023-02-20 04:32 UTC by DadhichTanishka

2023-02-20 04:46 UTC, PatelNeelMahesh approved these changes
You should remove the default readme file and update your project description and figma link and should update it as you add more features.

In src folder for you can remove default testing files.

2023-02-20 04:48 UTC, PatelNeelMahesh commented
You should give better commit message.
Instead of "first pull" you can write "Initialized react app, created landing page & navbar"

2023-02-20 05:49 UTC, aditya-190 commented on frontend/README.md
> +
Update your README  -

Add  brief description about your project.
You can also add a checklist that can be used to track all the topics covered until now.

For reference - https://github.com/kalviumcommunity/openbadgx/blob/main/README.md

2023-02-20 05:51 UTC, aditya-190 commented on frontend/package.json
> +    "@testing-library/user-event": "^13.5.0",
It is advisable to include testing libraries in the devDependencies section, as failing to do so may result in their being bundled into the React application, consequently leading to an increase in the overall bundle size.

Reference -> https://www.geeksforgeeks.org/difference-between-dependencies-devdependencies-and-peerdependencies/

2023-02-20 05:52 UTC, aditya-190 commented on frontend/package.json
> +  "name": "capstone",
Update the name to ClosetGenie

2023-02-20 05:52 UTC, aditya-190 commented on frontend/public/manifest.json
> +  "name": "Create React App Sample",
Update the name to ClosetGenie

2023-02-20 05:54 UTC, aditya-190 commented on frontend/src/App.js
> +// import NavBar from './navbar';
Please remove the redundant comments.

2023-02-20 05:55 UTC, aditya-190 requested changes
Please address the comments before merging. Everything else LGTM.

2023-02-21 09:41 UTC, DadhichTanishka commented
I have made the changes please check them.

2023-02-21 10:17 UTC, aditya-190 approved these changes
LGTM. Proceed with merging

2023-02-21 12:11 UTC, merged